apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ssp
    annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: admin.contextsuite.com
        nginx.ingress.kubernetes.io/enable-cors: "true"

spec:
    rules:
        - host: admin.contextsuite.com
          http:
              paths:
                  - backend:
                        service:
                            name: ssp
                            port:
                                number: 8080
                    path: /
                    pathType: Prefix

    tls:
        - hosts:
              - admin.contextsuite.com
          secretName: star-contextsuite-com
