apiVersion: v1
kind: Service
metadata:
  name: cxsservices
  labels:
    app: cxsservices
    tier: api
spec:
  type: NodePort
  ports:
    - port: 8088
  selector:
    app: cxsservices
    tier: api
