# Credentials for authentication
auth:
  ZO_ROOT_USER_EMAIL: "tommi@snjallgogn.is"
  ZO_ROOT_USER_PASSWORD: "TempPasswordReplacedRightAfterInstall"

fullnameOverride: openobserve

service:
  annotations:
    tailscale.com/expose: "true"
