apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicerunner
spec:
  selector:
    matchLabels:
      app: servicerunner
      tier: api
  template:
    metadata:
      labels:
        app: servicerunner
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/service-runner:0e784c3
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8088
          livenessProbe:
            httpGet:
              port: 8088
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8088
              path: /api/status/ready
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: contextsuite
                key: CLICKHOUSE_PASSWORD
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm
                key: OPENAI_API_KEY
          envFrom:
            - configMapRef:
                name: servicerunner-config
      imagePullSecrets:
        - name: dockerlock

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: servicerunner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicerunner
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 60