apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: cxs-onenote-auth-pvc
  name: cxs-onenote-auth-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
