apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

configMapGenerator:
  - name: grafana-longhorn-alerts
    files:
      - storage-alerting.yaml=longhorn-rules.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
    

resources: []