apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

configMapGenerator:
  - name: grafana-longhorn-alerts
    files:
      - longhorn-rules.yaml=longhorn-rules.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-test-alerts
    files:
      - test-rule.yaml=test-rule.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
    

resources: []