apiVersion: 1
groups:
  - name: test
    folder: General
    interval: 1m
    rules:
      - uid: always-firing
        title: Always firing
        condition: A > 0
        data:
          - refId: A
            datasourceUid: fefbtw5xi6n0gd
            model:
              expr: vector(1)
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        annotations:
          summary: This is always firing
