# How to use secrets in loki helm chart
# https://github.com/grafana/loki/issues/8572
backend:
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_LOKI_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_ACCESS_KEY_ID
    - name: S3_LOKI_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_SECRET_ACCESS_KEY

write:
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_LOKI_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_ACCESS_KEY_ID
    - name: S3_LOKI_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_SECRET_ACCESS_KEY

read:
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_LOKI_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_ACCESS_KEY_ID
    - name: S3_LOKI_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_SECRET_ACCESS_KEY
loki:
  storage:
    type: "s3"
    s3:
      s3: null
      endpoint: http://minio.storage.svc.cluster.local:9025
      region: null
      accessKeyId: "${S3_LOKI_ACCESS_KEY_ID}"
      secretAccessKey: "${S3_LOKI_SECRET_ACCESS_KEY}"
      s3ForcePathStyle: true
      insecure: true
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-ruler"
      admin: "loki-admin"
