apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

configMapGenerator:
  - name: grafana-longhorn-alerts
    files:
      - longhorn_space_alerts.yaml
    options:
      disableNameSuffixHash: true

resources: []
