# Persistent Volume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-pv
  namespace: pipelines
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nifi
---
# Persistent Volume Claim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-pvc
  namespace: pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: nifi-secret
  namespace: pipelines
type: Opaque
data:
  single_user_credentials_password: bmlmaUBzbmphbGxnb2du
---  
# NiFi Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi:2.0.0-M4
          env:
            - name: NIFI_UI_BANNER_TEXT
              value: snjallgogn
            - name: SINGLE_USER_CREDENTIALS_USERNAME
              value: admin
            - name: SINGLE_USER_CREDENTIALS_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: nifi-secret 
                  key: single_user_credentials_password 
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: nifi-storage
              mountPath: /opt/nifi/nifi-current/logs
      volumes:
        - name: nifi-storage
          persistentVolumeClaim:
            claimName: nifi-pvc
---
# NiFi Service
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  namespace: pipelines
spec:
  type: LoadBalancer
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: nifi
