# NiFi Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi:2.0.0-M4
          env:
            - name: NIFI_WEB_PROXY_HOST
              value: nifi.contextsuite.com
            - name: NIFI_UI_BANNER_TEXT
              value: snjallgogn
            - name: SINGLE_USER_CREDENTIALS_USERNAME
              value: admin
            - name: SINGLE_USER_CREDENTIALS_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: nifi-secret 
                  key: single_user_credentials_password 
          ports:
            - containerPort: 8443
---
# Opaque Secret
apiVersion: v1
kind: Secret
metadata:
  name: nifi-secret
  namespace: pipelines
type: Opaque
data:
  single_user_credentials_password: bmlmaUBzbmphbGxnb2du # base64 encoded
---  
# NiFi Service
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
spec:
  type: ClusterIP
  selector:
    app: nifi
  ports:
    - port: 8443
      targetPort: 8443
