apiVersion: v1
kind: Service
metadata:
  name: translator-client
  labels:
    app: translator-client
    tier: web
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: translator-client
    tier: web
