apiVersion: v1
kind: Service
metadata:
  name: cxs-mimir-chat-web
  labels:
    app: cxs-mimir-chat-web
    tier: web
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: cxs-mimir-chat-web
    tier: web
