images:
  - name: quicklookup/contextapi
    newTag: "87861e3"

resources:
  - ../../base
patches:
  - path: contextapi-config.yaml
  - target:
      kind: Ingress
      name: contextapi
    patch: |
      - "op": replace
        "path": /spec/rules/0/host
        "value": &fqdn app.staging.contextsuite.com
      - "op": replace
        "path": /spec/tls/0/hosts/0
        "value": *fqdn  # <- this is a YAML anchor
      
