apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formapi
spec:
  rules:
    - host: form.contextsuite.com
      http:
        paths:
          - backend:
              service:
                name: formapi
                port:
                  number: 3001
            path: /stats
            pathType: Prefix
          - backend:
              service:
                name: formapi
                port:
                  number: 3001
            path: /context
            pathType: Prefix
          - backend:
              service:
                name: formapi
                port:
                  number: 3001
            path: /graph
            pathType: Prefix
  tls:
    - hosts:
        - form.contextsuite.com
      secretName: star-contextsuite-com
