apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cxs-mimir-web-logreglan-static
  namespace: solutions
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: leo.logreglan.is
      http:
        paths:
          # Static assets - NO rewrite
          - path: /_next
            pathType: Prefix
            backend:
              service:
                name: cxs-mimir-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cxs-mimir-web
                port:
                  number: 3000
          - path: /manifest.webmanifest
            pathType: Prefix
            backend:
              service:
                name: cxs-mimir-web
                port:
                  number: 3000
  tls:
    - hosts:
        - leo.logreglan.is
      secretName: leo-logreglan-is-tls
---
# Separate Ingress for rewrite to avoid conflicts
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cxs-mimir-web-logreglan-app
  namespace: solutions
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /logreglan/$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: leo.logreglan.is
      http:
        paths:
          # App routes - negative lookahead to exclude static paths
          - path: /(?!_next|api|manifest\.webmanifest)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cxs-mimir-web
                port:
                  number: 3000
  tls:
    - hosts:
        - leo.logreglan.is
      secretName: leo-logreglan-is-tls