apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir-chat-web
spec:
  rules:
    - host: agents.contextsuite.com
      http:
        paths:
          - backend:
              service:
                name: mimir-chat-web
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - agents.contextsuite.com
      secretName: star-contextsuite-com
