apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  selector:
    matchLabels:
      app: ingress
      tier: api
  replicas: 3
  template:
    metadata:
      labels:
        app: ingress
        tier: api
    spec:
      containers:
      - name: ingress
        image: quicklookup/ingress:v1.0.53
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 2222
          name: sftp
        restartPolicy: Never
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: NEO4J_PASSWORD
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: REDIS_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_SECRET_KEY
        envFrom:
          - configMapRef:
              name: ingress-config
        volumeMounts:
          - mountPath: /tmp
            name: sftp
          - mountPath: /tmp/hostkey.ser
            subPath: hostkey.ser
            name: config-volume

      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: config-volume
          configMap:
            name: ingress-config
        - hostPath:
            path: /data/s3/ingress
          name: sftp
