apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  hostkey.ser: |-    
    $(PKEY_SFTP)

  ## Kafka
  KAFKA_URI: 'kafka.data:9092'
  KAFKA_HOST: 'kafka.data'
  KAFKA_PORT: '9092'

  ## Redis
  REDIS_HOST: 'redis-master.data'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_LOCAL: 'true'

  ## Postgres
  POSTGRES_HOST: 'cxs-pg-pgbouncer.data'
  POSTGRES_URI: 'jdbc:postgresql://cxs-pg-pgbouncer.data:5432/ssp'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'ssp'
  POSTGRES_USER: 'cxs'

  # Neo4j
  NEO4J_URI: 'neo4j://neo4j.data:7687'
  NEO4J_HOST: 'neo4j.data'
  NEO4J_USER: 'admin'
  NEO4J_DATABASE: 'contextsuite'

  S3_REGION: 'ams3'
  S3_ENDPOINT: 'https://cxs.ingression.ams3.digitaloceanspaces.com'

  SPRING_PROFILES_ACTIVE: 'dev'