resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: contextsuite
    patch: |
      - "op": replace
        "path": /spec/template/spec/containers/0/image
        "value": "quicklookup/contextsuite:82b25bb"

