apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: isl-hotel-streaming-client
  name: offset-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
