images:
  - name: quicklookup/contextsuite
    newTag: 82b25bb

resources:
  - ../../base
patches:
  - path: contextsuite-config.yaml
  - target:
      kind: Ingress
      name: contextsuite
    patch: |
      - "op": replace
        "path": /spec/rules/0/host
        "value": &fqdn app-staging.contextsuite.com
      - "op": replace
        "path": /spec/tls/0/hosts/0
        "value": *fqdn  # <- this is a YAML anchor
